### ISSUE TITLE
Trying to test locally. I created a user on the console. Got an error

### ISSUE THREAD

**Issue by heyapricot** [dipto0321/facialbook#5]
![Screen Shot 2019-05-16 at 09 41 14](https://user-images.githubusercontent.com/14355495/57863009-ede1ca80-77be-11e9-96ae-ce56d9388599.png)

**Comment by dipto0321** [comment]
Hi @heyapricot ,

If you want to create a `user` from the console. You have to do it like this way.
```ruby
User.create(
  email: 'john.doe@gmail.com',
  password: 'password',
  password_confirmation: 'password',
  profile_attributes: {
    first_name: 'John',
    last_name: 'Doe',
    birthday: Faker::Date.birthday,
    gender: 'male'
  }
)
```
Without `profile_attributes:` it will create a user from console but raise an error in UI. We are still trying to figure out how we can stop users without passing any `profile_attributes` to create a new user from the console. I am mentioning the `console` because it's not possible for a user to sign_up without passing  first_name,  last_name, birthday, gender, etc from the UI.

![2019-05-19_142255](https://user-images.githubusercontent.com/6507903/57980337-3feb5000-7a4c-11e9-858a-407dc21eb05b.jpg)

Thanks 🙏

**Comment by rvvergara** [comment]
@heyapricot  it's because we made profile a nested attribute under user. This was one of the points you raised when you first reviewed our project some months back. We have tried `reject_if ...` but it appears creating a user in the console won't be stopped unless we develop a special method (which in this case is a little redundant considering we have the necessary protection in the User Interface).

**Comment by rvvergara** [comment]
@heyapricot, in relation to this and @dipto0321 's reply [we have added a `before_validation` callback](https://github.com/dipto0321/facialbook/blob/66ddc0daa5dc123315888693db51c214ed0f780c/app/models/user.rb#L42) into our `user.rb` to disallow creation of a user account without completing all the necessary profile information.

![image](https://user-images.githubusercontent.com/6015315/57982219-cddb3100-7a74-11e9-9f1d-d886e5f6292d.png)

Now we have added another layer of protection (already provided at the controller level) for making sure users create their profiles (with complete information, errors would still happen if user doesn't complete all attributes for the profile model). For instance:

![image](https://user-images.githubusercontent.com/6015315/57982188-8eace000-7a74-11e9-9875-e30fdf61020a.png)

If then you input all required profile attributes then user is valid:

![image](https://user-images.githubusercontent.com/6015315/57982403-c0737600-7a77-11e9-80f4-4b307c2ef5f4.png)

**Comment by rvvergara** [comment]
Issue is now resolved. User account won't happen unless profile is also created.
